name: template

on:
  workflow_call:
    inputs:
      can-apply-terraform-plan:
         type: boolean
         description: "Indicates whether terraform changes can be applied or not"
         required: false
         default: true

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - name: Output Inputs
        run: echo "${{ toJSON(inputs) }}"

  greet:
    if: ${{ inputs.can-apply-terraform-plan == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/config-to-env
        with:
          environment: test
      - run: env
      - name: amp cli login
        run: echo "Hello ${{ env.key1 }}"
