name: template

on:
  workflow_call:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: .github/actions/config-to-env@latest
        with:
          environment: test
      - run: env
      - name: amp cli login
        run: echo "Hello World"
