name: Deploy Datafactory

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - name: Pause for 25 seconds
        run: |
          sleep 25
      - name: fail for testing
        run: |
          exit 1