name: ${{ inputs.title }}

on:
  workflow_dispatch:
    inputs:
      title:
        required: true
        description: title
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - name: Pause for 25 seconds
        run: |
          sleep 25
