name: Manual workflow

on:
  workflow_dispatch:
   inputs:
    enableManualDeployement :
      description: 'Click to enable manual deployment from a custom branch to the test environment.'
      type: boolean
      default: false
      required: true
env:
  test: sandbox
  preprod: dev
  actual: test
jobs:
  new:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/identify-modified-components
        name: Identify modified components
      - run: |
          echo -e "\e[1;31m::group::Logs of pod"
          echo "random logs"
          echo "::endgroup::"
