name: Manual workflow

on:
  workflow_dispatch:
   inputs:
    enableManualDeployement :
      description: 'Click to enable manual deployment from a custom branch to the test environment.'
      type: boolean
      default: false
      required: true
env:
  test: sandbox
  preprod: dev
  actual: test
jobs:
  new:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: |
          echo -e "\e[1;31m::group::Logs of pod"
          echo "rondom logs"
          echo "::endgroup::"
