name: Manual workflow

on:
  workflow_dispatch:
   inputs:
    enableManualDeployement :
      description: 'Click to enable manual deployment from a custom branch to the test environment.'
      type: boolean
      default: false
      required: true
  
jobs:
  new:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - uses: actions/checkout@v2
      - uses: ./.github/actions/find-last-release
      - run: env
